(async()=>{
const order=['01-case-presentation','02-first-decision','07-investigations','03-normal-physiology','04-disruption','05-symptoms','06-signs','08-treatment','10-synthesis'];
const labels=['Case presentation','Clinical reasoning','Investigations','Normal insulin physiology','Insulin deficiency','Symptoms','Signs','Treatment','Reconstruct the case'];
let data={stages:[]};try{data=await fetch(new URL('narration/dka.json',document.baseURI),{cache:'no-cache'}).then(r=>{if(!r.ok)throw new Error(`Narration ${r.status}`);return r.json()})}catch(e){}
const scripts=Object.fromEntries((data.stages||[]).map(s=>[s.id,s.script||'']));
const css=`.speech-orb{position:fixed!important;z-index:2147483647!important;right:16px!important;bottom:86px!important;width:66px;height:66px;border:1px solid #ffd978;border-radius:50%;display:grid;place-items:center;padding:0;color:#161009;background:radial-gradient(circle at 32% 25%,#fff8d8 0 6%,#ffe39a 7% 14%,#f3bd45 27%,#d98d12 58%,#8a4b07 82%,#4b2502 100%);box-shadow:inset 5px 6px 9px #fff9,inset -7px -9px 13px #4e250899,0 4px 0 #754007,0 13px 34px #000b;cursor:pointer;touch-action:manipulation;-webkit-tap-highlight-color:transparent;transform-origin:center}.speech-orb:after{content:'';position:absolute;inset:5px;border-radius:50%;border:1px solid #fff5}.speech-orb svg{position:relative;z-index:2;width:31px;height:31px;filter:drop-shadow(0 1px 0 #fff5)}.speech-orb.discover{animation:discoverPulse 1.55s ease-in-out infinite}.speech-orb.discover:before{content:'';position:absolute;inset:-5px;border:2px solid #e9a51b;border-radius:50%;animation:discoverRing 1.55s ease-out infinite}.speech-orb.playing{box-shadow:inset 5px 6px 9px #fff9,inset -7px -9px 13px #4e250899,0 4px 0 #754007,0 0 0 7px #e9a51b20,0 13px 34px #000b}.speech-panel{position:fixed!important;z-index:2147483646!important;right:12px;bottom:164px;width:min(370px,calc(100vw - 24px));display:none;padding:14px;border:1px solid #e9a51b55;border-radius:16px;background:#10100ef7;color:#f0eee8;box-shadow:0 16px 42px #000c;backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px)}.speech-panel.open{display:block}.speech-title{font-size:12px;font-weight:800}.speech-sub{font-size:8px;color:#e9a51b;text-transform:uppercase;letter-spacing:.13em;margin-bottom:5px}.speech-controls{display:flex;gap:6px;margin-top:11px;flex-wrap:wrap}.speech-controls button{height:36px;min-width:48px;padding:0 11px;border:1px solid #ffffff25;border-radius:999px;background:#ffffff08;color:#f0eee8;font-weight:700;touch-action:manipulation}.speech-controls button.active{background:#e9a51b;color:#0a0907;border-color:#e9a51b}.speech-progress{height:3px;background:#ffffff18;margin-top:11px;border-radius:4px;overflow:hidden}.speech-progress i{display:block;height:100%;width:0;background:#e9a51b}.speech-fallback{display:inline-block;margin-top:11px;color:#e9a51b;font-size:11px;text-decoration:underline;text-underline-offset:3px}.live-cc{position:fixed!important;z-index:2147483645!important;left:50%;transform:translateX(-50%);bottom:164px;width:min(680px,calc(100vw - 30px));display:none;text-align:center;padding:11px 16px;border-radius:10px;background:#050505e8;color:#fff;font-size:15px;line-height:1.4;box-shadow:0 8px 28px #0009;pointer-events:none}.live-cc.open{display:block}@keyframes discoverPulse{0%,100%{transform:scale(1)}50%{transform:scale(1.1)}}@keyframes discoverRing{0%{opacity:.9;transform:scale(.96)}75%,100%{opacity:0;transform:scale(1.55)}}@media(max-width:600px){.speech-panel{right:8px;bottom:160px;width:calc(100vw - 16px)}.live-cc{bottom:162px;font-size:14px;width:calc(100vw - 24px)}}`;
const st=document.createElement('style');st.textContent=css;document.head.append(st);
const orb=document.createElement('button');orb.className='speech-orb discover';orb.type='button';orb.setAttribute('aria-label','Play case audio. Hold for audio options.');orb.innerHTML='<svg viewBox="0 0 24 24"><path fill="currentColor" d="M12 3a8 8 0 0 0-8 8v6a3 3 0 0 0 3 3h2v-8H6v-1a6 6 0 0 1 12 0v1h-3v8h2a3 3 0 0 0 3-3v-6a8 8 0 0 0-8-8Zm-5 11h1v4H7a1 1 0 0 1-1-1v-2a1 1 0 0 1 1-1Zm10 0a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-1v-4h1Z"/></svg>';
const panel=document.createElement('div');panel.className='speech-panel';panel.innerHTML='<div class="speech-sub">Audio settings</div><div class="speech-title"></div><div class="speech-controls"><button type="button" data-rate="1" class="active">1×</button><button type="button" data-rate="1.25">1.25×</button><button type="button" data-rate="1.5">1.5×</button><button type="button" data-rate="2">2×</button><button type="button" data-x="cc">CC</button></div><div class="speech-progress"><i></i></div><a class="speech-fallback" target="_blank" rel="noopener">Open in device audio player</a>';
const cc=document.createElement('div');cc.className='live-cc';cc.setAttribute('role','status');cc.setAttribute('aria-live','off');document.body.append(orb,panel,cc);
const audio=document.createElement('audio');audio.preload='auto';audio.playsInline=true;audio.setAttribute('playsinline','');audio.setAttribute('webkit-playsinline','');document.body.append(audio);
let i=0,rate=1,holdTimer=null,suppressClick=false,ccOn=false;const title=panel.querySelector('.speech-title'),bar=panel.querySelector('.speech-progress i'),fallback=panel.querySelector('.speech-fallback');
function audioUrl(){return new URL(`audio/dka/${order[i]}.mp3`,document.baseURI).href}
function words(){return (scripts[order[i]]||'').trim().split(/\s+/).filter(Boolean)}
function updateCC(){if(!ccOn){cc.textContent='';return}const w=words();if(!w.length){cc.textContent='';return}const frac=audio.duration&&isFinite(audio.duration)?Math.min(1,audio.currentTime/audio.duration):0;const center=Math.min(w.length-1,Math.floor(frac*w.length));const start=Math.max(0,center-5),end=Math.min(w.length,center+7);cc.textContent=w.slice(start,end).join(' ')}
function sync(){title.textContent=labels[i];bar.style.width='0';fallback.href=audioUrl();updateCC()}
function markPlayFailure(error){orb.classList.remove('playing');panel.classList.add('open');title.textContent=error&&error.name==='NotAllowedError'?'Tap the gold button again to start audio':'Audio could not start — use the device player below'}
function play(){audio.muted=false;audio.volume=1;audio.playbackRate=rate;const result=audio.play();if(result&&typeof result.then==='function')result.then(()=>orb.classList.add('playing')).catch(markPlayFailure)}
function load(shouldPlay=false){audio.pause();audio.src=audioUrl();audio.load();sync();if(shouldPlay)play()}
function acknowledge(){orb.classList.remove('discover')}
function toggle(){acknowledge();if(audio.paused){if(audio.error)load(false);play()}else{audio.pause();orb.classList.remove('playing')}}
function beginHold(){suppressClick=false;clearTimeout(holdTimer);holdTimer=setTimeout(()=>{suppressClick=true;acknowledge();panel.classList.toggle('open');if(navigator.vibrate)navigator.vibrate(20)},520)}
function endHold(){clearTimeout(holdTimer)}
orb.addEventListener('pointerdown',beginHold);orb.addEventListener('pointerup',endHold);orb.addEventListener('pointercancel',endHold);orb.addEventListener('pointerleave',endHold);orb.addEventListener('click',e=>{e.preventDefault();if(suppressClick){suppressClick=false;return}toggle()});orb.addEventListener('contextmenu',e=>e.preventDefault());
panel.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;const rateValue=button.dataset.rate;if(rateValue){rate=Number(rateValue);audio.playbackRate=rate;panel.querySelectorAll('[data-rate]').forEach(b=>b.classList.toggle('active',b===button));return}if(button.dataset.x==='cc'){ccOn=!ccOn;cc.classList.toggle('open',ccOn);button.classList.toggle('active',ccOn);updateCC()}});
audio.ontimeupdate=()=>{if(audio.duration){bar.style.width=(100*audio.currentTime/audio.duration)+'%';updateCC()}};audio.onplay=()=>{acknowledge();orb.classList.add('playing');orb.setAttribute('aria-label','Pause case audio. Hold for audio options.')};audio.onpause=()=>{orb.classList.remove('playing');orb.setAttribute('aria-label','Play case audio. Hold for audio options.')};audio.onended=()=>{orb.classList.remove('playing');if(i<order.length-1){i++;load(true)}else updateCC()};audio.onerror=()=>{orb.classList.remove('playing');panel.classList.add('open');title.textContent='Recording unavailable — open it in the device player below'};load(false);
window.MeducateAudio={orb,panel,toggle,audio};
})();
