(async()=>{
const css=`
.commentary-fab{position:fixed;z-index:160;right:24px;bottom:96px;width:60px;height:60px;border:1px solid #f2bd55;border-radius:50%;display:none;place-items:center;padding:0;color:#111;background:radial-gradient(circle at 31% 24%,#fff3bd 0 7%,#f7ca62 15%,#e9a51b 46%,#bd7310 76%,#6d3b05 100%);box-shadow:inset 5px 6px 10px #fff7,inset -8px -10px 14px #61330199,0 5px 0 #7a4708,0 14px 32px #0009;cursor:pointer;touch-action:none;user-select:none;-webkit-user-select:none;transition:transform .16s ease,box-shadow .16s ease}.commentary-fab:after{content:"";position:absolute;inset:4px;border-radius:50%;border:1px solid #fff4;box-shadow:inset 0 0 0 1px #6d3b052e;pointer-events:none}.commentary-fab.visible{display:grid}.commentary-fab.discover{animation:commentDiscover 1.85s ease-in-out infinite}.commentary-fab.discover:before{content:"";position:absolute;inset:-3px;border:2px solid #e9a51b;border-radius:50%;pointer-events:none;animation:commentRing 1.85s ease-out infinite}.commentary-fab.playing:not(.discover){animation:commentPulse 1.65s ease-in-out infinite}.commentary-fab.holding{transform:translateY(2px) scale(.97);box-shadow:inset 4px 5px 10px #fff5,inset -7px -9px 13px #61330199,0 2px 0 #7a4708,0 8px 22px #0008}.commentary-fab svg{position:relative;z-index:2;width:29px;height:29px;filter:drop-shadow(0 1px 0 #fff7)}
.commentary-hold{position:fixed;z-index:159;right:12px;bottom:166px;display:none;align-items:center;gap:6px;padding:7px 8px;border:1px solid #ffffff26;border-radius:999px;background:#11110feF;color:#f0eee8;box-shadow:0 12px 34px #0009;backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px)}.commentary-hold.open{display:flex}.commentary-hold button{height:36px;min-width:36px;padding:0 10px;border:1px solid #ffffff20;border-radius:999px;background:#ffffff08;color:#f0eee8;font:inherit;font-size:10px;font-weight:800;letter-spacing:.03em;white-space:nowrap}.commentary-hold button.selected,.commentary-hold button.hovered{border-color:#e9a51b;color:#f7c55d;background:#e9a51b18}.commentary-hold .cc{min-width:48px}.commentary-status{max-width:110px;padding:0 6px;color:#aaa69e;font-size:8px;line-height:1.25;letter-spacing:.07em;text-transform:uppercase}.commentary-status strong{display:block;color:#f0eee8;font-size:8px}.commentary-hint{position:fixed;z-index:158;right:18px;bottom:72px;display:none;padding:5px 8px;border-radius:999px;background:#11110fe8;color:#aaa69e;font-size:9px;letter-spacing:.05em}.commentary-hint.show{display:block}
.commentary-caption{position:fixed;z-index:157;left:50%;bottom:18px;transform:translateX(-50%) translateY(10px);width:min(720px,calc(100vw - 112px));max-height:90px;overflow:hidden;padding:9px 13px;border:1px solid #ffffff1d;border-radius:10px;background:#0d0d0ccd;color:#a9a69f;box-shadow:0 7px 24px #0006;backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);font-size:13px;line-height:1.42;opacity:0;visibility:hidden;transition:opacity .18s ease,transform .18s ease;pointer-events:none}.commentary-caption.open{opacity:1;visibility:visible;transform:translateX(-50%) translateY(0)}.commentary-caption .cap-label{display:block;margin-bottom:2px;color:#e9a51b;font-size:8px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}.commentary-caption .spoken{color:#f4f0e8}
@keyframes commentPulse{50%{box-shadow:inset 5px 6px 10px #fff7,inset -8px -10px 14px #61330199,0 5px 0 #7a4708,0 0 0 8px #e9a51b18,0 14px 32px #0009}}@keyframes commentDiscover{0%,100%{transform:scale(1)}50%{transform:scale(1.085)}}@keyframes commentRing{0%{opacity:.78;transform:scale(1)}80%,100%{opacity:0;transform:scale(1.65)}}
@media(prefers-reduced-motion:reduce){.commentary-fab.discover,.commentary-fab.discover:before,.commentary-fab.playing{animation:none}.commentary-fab.discover{outline:4px solid #e9a51b26}}
@media(max-width:600px){.commentary-fab{right:14px;bottom:90px;width:54px;height:54px}.commentary-fab svg{width:26px;height:26px}.commentary-hold{right:8px;bottom:153px;max-width:calc(100vw - 16px);gap:4px;padding:6px}.commentary-hold button{height:34px;min-width:34px;padding:0 8px;font-size:9px}.commentary-status{display:none}.commentary-hint{right:12px;bottom:63px}.commentary-caption{left:10px;bottom:16px;width:calc(100vw - 82px);transform:translateY(10px);font-size:12px;max-height:78px;padding:8px 10px}.commentary-caption.open{transform:translateY(0)}}
`;
const style=document.createElement('style');style.textContent=css;document.head.append(style);
let lesson;
try{lesson=await fetch('narration/dka.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()})}catch(e){console.error('Narration source unavailable',e);return}
const stages=lesson.stages||[];
const fab=document.createElement('button');fab.className='commentary-fab';fab.type='button';fab.setAttribute('aria-label','Play or pause lecturer audio. Press and hold for options.');fab.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 3a8 8 0 0 0-8 8v6a3 3 0 0 0 3 3h2v-8H6v-1a6 6 0 0 1 12 0v1h-3v8h2a3 3 0 0 0 3-3v-6a8 8 0 0 0-8-8Zm-5 11h1v4H7a1 1 0 0 1-1-1v-2a1 1 0 0 1 1-1Zm10 0a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-1v-4h1Z"/></svg>';
const hint=document.createElement('div');hint.className='commentary-hint';hint.textContent='Tap for audio · Hold for options';
const hold=document.createElement('div');hold.className='commentary-hold';hold.setAttribute('aria-hidden','true');hold.innerHTML=`<button type="button" data-action="restart" aria-label="Restart">↺</button><button type="button" data-speed="0.85">0.85×</button><button type="button" data-speed="1">1×</button><button type="button" data-speed="1.15">1.15×</button><button type="button" class="cc" data-action="captions" aria-label="Toggle live transcript">CC</button><div class="commentary-status"><strong>Audio</strong><span>Ready</span></div>`;
const caption=document.createElement('div');caption.className='commentary-caption';caption.setAttribute('aria-live','polite');caption.innerHTML='<span class="cap-label">Live transcript</span><span class="cap-text"></span>';
document.body.append(fab,hint,hold,caption);
const statusText=hold.querySelector('.commentary-status span'),capText=caption.querySelector('.cap-text'),captionButton=hold.querySelector('[data-action="captions"]'),backdrop=document.querySelector('.backdrop');
let lastStep=-1,audio=null,utter=null,paused=false,usingRecording=false,fallbackStarted=false,rate=1,holdTimer=null,didHold=false,hovered=null,captionTimer=null,captionOn=false,segments=[];
let discovered=false;try{discovered=localStorage.getItem('meducateme-commentary-discovered')==='1';captionOn=localStorage.getItem('meducateme-live-transcript')==='1'}catch{}
function activeStep(){const els=[...document.querySelectorAll('.lesson-stage')];return Math.max(0,els.findIndex(s=>s.classList.contains('active')))}
function current(){return stages[activeStep()]||stages[0]}
function markDiscovered(){if(discovered)return;discovered=true;fab.classList.remove('discover');hint.classList.remove('show');try{localStorage.setItem('meducateme-commentary-discovered','1')}catch{}}
function updateControls(){hold.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.speed)===rate));captionButton.classList.toggle('selected',captionOn);captionButton.textContent=captionOn?'CC ✓':'CC'}
function setStatus(text){statusText.textContent=text}
function stopCaptionClock(){if(captionTimer){clearInterval(captionTimer);captionTimer=null}}
function resetButton(){fab.classList.remove('playing');paused=false;stopCaptionClock()}
function stop(){if(audio){audio.pause();audio.currentTime=0;audio=null}if('speechSynthesis'in window)window.speechSynthesis.cancel();utter=null;usingRecording=false;fallbackStarted=false;resetButton();renderCaption(0)}
function setPlaying(){fab.classList.add('playing');paused=false;startCaptionClock()}
function chooseVoice(){const vs=window.speechSynthesis?.getVoices?.()||[];return vs.find(v=>/en-GB/i.test(v.lang)&&/male|daniel|george|ryan|arthur|oliver/i.test(v.name))||vs.find(v=>/en-GB/i.test(v.lang))||vs.find(v=>/^en/i.test(v.lang))||vs[0]}
function buildSegments(){const s=current()?.script||'';segments=s.match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.map(x=>x.trim()).filter(Boolean)||[s];renderCaption(0)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderCaption(index){if(!captionOn){caption.classList.remove('open');return}caption.classList.add('open');if(!segments.length)buildSegments();const i=Math.max(0,Math.min(index,segments.length-1));const before=i>0?segments[i-1]+' ':'';const now=segments[i]||'';const after=i+1<segments.length?' '+segments[i+1]:'';capText.innerHTML=`${escapeHtml(before)}<span class="spoken">${escapeHtml(now)}</span>${escapeHtml(after)}`}
function captionIndexFromPlayback(){if(!segments.length)return 0;if(usingRecording&&audio&&Number.isFinite(audio.duration)&&audio.duration>0)return Math.min(segments.length-1,Math.floor((audio.currentTime/audio.duration)*segments.length));return 0}
function startCaptionClock(){stopCaptionClock();if(!captionOn)return;renderCaption(captionIndexFromPlayback());captionTimer=setInterval(()=>{if(usingRecording&&audio)renderCaption(captionIndexFromPlayback())},240)}
function fallbackSpeak(){if(fallbackStarted)return;fallbackStarted=true;usingRecording=false;setStatus('Device voice');if(!('speechSynthesis'in window)){resetButton();return}const s=current()?.script||'';window.speechSynthesis.cancel();utter=new SpeechSynthesisUtterance(s);utter.lang='en-GB';utter.rate=rate;utter.pitch=.82;const v=chooseVoice();if(v)utter.voice=v;utter.onboundary=e=>{if(!captionOn||e.name!=='word')return;let chars=0,idx=0;for(let i=0;i<segments.length;i++){chars+=segments[i].length+1;if(e.charIndex<chars){idx=i;break}}renderCaption(idx)};utter.onend=()=>{utter=null;fallbackStarted=false;resetButton()};utter.onerror=()=>{utter=null;fallbackStarted=false;resetButton()};window.speechSynthesis.speak(utter);setPlaying()}
function playCurrent(restartFromStart=false){const stage=current();if(!stage)return;if(paused&&!restartFromStart){if(usingRecording&&audio){audio.playbackRate=rate;audio.play().then(setPlaying).catch(()=>fallbackSpeak());return}if(!usingRecording&&'speechSynthesis'in window){speechSynthesis.resume();setPlaying();return}}stop();fallbackStarted=false;buildSegments();audio=new Audio(`audio/dka/${stage.id}.mp3`);audio.preload='auto';audio.playbackRate=rate;usingRecording=true;setStatus('Recorded voice');let failed=false;const fail=()=>{if(failed)return;failed=true;if(audio){audio.pause();audio=null}fallbackSpeak()};audio.onerror=fail;audio.onended=()=>{audio=null;usingRecording=false;resetButton()};const p=audio.play();if(p&&p.then)p.then(setPlaying).catch(fail);else setPlaying()}
function pauseCurrent(){if(usingRecording&&audio&&!audio.paused){audio.pause();paused=true;fab.classList.remove('playing');stopCaptionClock();return true}if(!usingRecording&&'speechSynthesis'in window&&speechSynthesis.speaking&&!speechSynthesis.paused){speechSynthesis.pause();paused=true;fab.classList.remove('playing');stopCaptionClock();return true}return false}
function togglePlay(){markDiscovered();if(!pauseCurrent())playCurrent(false)}
function toggleCaptions(){captionOn=!captionOn;try{localStorage.setItem('meducateme-live-transcript',captionOn?'1':'0')}catch{};updateControls();if(captionOn){buildSegments();renderCaption(captionIndexFromPlayback());if(fab.classList.contains('playing'))startCaptionClock()}else{caption.classList.remove('open');stopCaptionClock()}}
function sync(){const i=activeStep();if(i!==lastStep){stop();lastStep=i;buildSegments();setStatus('Ready')}}
function updateVisibility(){const open=!!backdrop?.classList.contains('open');fab.classList.toggle('visible',open);fab.classList.toggle('discover',open&&!discovered);hint.classList.toggle('show',open&&!discovered);caption.classList.toggle('open',open&&captionOn);if(!open){stop();hideHold();caption.classList.remove('open')}}
function showHold(){markDiscovered();didHold=true;fab.classList.add('holding');hold.classList.add('open');hold.setAttribute('aria-hidden','false');updateControls()}
function hideHold(){clearTimeout(holdTimer);holdTimer=null;fab.classList.remove('holding');hold.classList.remove('open');hold.setAttribute('aria-hidden','true');if(hovered){hovered.classList.remove('hovered');hovered=null}}
function pickAt(x,y){const el=document.elementFromPoint(x,y)?.closest?.('.commentary-hold button');if(hovered&&hovered!==el)hovered.classList.remove('hovered');hovered=el||null;if(hovered)hovered.classList.add('hovered')}
function activate(el){if(!el)return;if(el.dataset.action==='restart'){playCurrent(true);return}if(el.dataset.action==='captions'){toggleCaptions();return}if(el.dataset.speed){rate=Number(el.dataset.speed);updateControls();if(usingRecording&&audio)audio.playbackRate=rate;else if('speechSynthesis'in window&&speechSynthesis.speaking){speechSynthesis.cancel();fallbackStarted=false;fallbackSpeak()}}}
fab.addEventListener('pointerdown',e=>{markDiscovered();didHold=false;clearTimeout(holdTimer);holdTimer=setTimeout(()=>{showHold();pickAt(e.clientX,e.clientY)},420);try{fab.setPointerCapture(e.pointerId)}catch{}});
fab.addEventListener('pointermove',e=>{if(didHold)pickAt(e.clientX,e.clientY)});
fab.addEventListener('pointerup',e=>{clearTimeout(holdTimer);if(didHold){pickAt(e.clientX,e.clientY);activate(hovered);hideHold();didHold=false}else togglePlay();try{fab.releasePointerCapture(e.pointerId)}catch{}});
fab.addEventListener('pointercancel',()=>{hideHold();didHold=false});fab.addEventListener('contextmenu',e=>e.preventDefault());
hold.querySelectorAll('button').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();activate(b)}));
const lessonScroll=document.querySelector('.lesson-scroll');if(lessonScroll)new MutationObserver(sync).observe(lessonScroll,{subtree:true,attributes:true,attributeFilter:['class']});if(backdrop)new MutationObserver(updateVisibility).observe(backdrop,{attributes:true,attributeFilter:['class']});
document.querySelector('.lesson-close')?.addEventListener('click',()=>{stop();hideHold();caption.classList.remove('open');setTimeout(updateVisibility,0)});document.querySelector('.lesson-next')?.addEventListener('click',()=>setTimeout(sync,0));document.querySelector('.lesson-prev')?.addEventListener('click',()=>setTimeout(sync,0));
updateControls();updateVisibility();sync();
})();
