(async()=>{
const css=`.commentary-fab{position:fixed;z-index:160;right:24px;bottom:96px;width:58px;height:58px;border:1px solid #e9a51b;border-radius:50%;background:#e9a51b;color:#0b0b0a;display:none;place-items:center;font-size:24px;box-shadow:0 12px 35px #0008;cursor:pointer}.commentary-fab.visible{display:grid}.commentary-fab.playing{animation:commentPulse 1.7s ease-in-out infinite}.commentary-panel{position:fixed;z-index:159;right:24px;bottom:166px;width:min(390px,calc(100vw - 32px));max-height:min(540px,calc(100svh - 250px));overflow:auto;padding:20px;border:1px solid #ffffff26;background:#11110ff5;color:#f0eee8;box-shadow:0 20px 60px #000b;display:none}.commentary-panel.open{display:block}.commentary-head{display:flex;align-items:center;gap:12px}.commentary-icon{width:42px;height:42px;border-radius:50%;background:#e9a51b;color:#0b0b0a;display:grid;place-items:center;font-size:20px}.commentary-title{flex:1}.commentary-title b{display:block;font-size:13px;letter-spacing:.08em}.commentary-title small{color:#a7a49d}.commentary-source{margin-top:5px;color:#e9a51b;font-size:9px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}.commentary-controls{display:grid;grid-template-columns:1.5fr 1fr 1fr;gap:7px;margin-top:16px}.commentary-controls button,.commentary-speed{min-height:40px;border:1px solid #ffffff2b;background:#ffffff08;color:#f0eee8;padding:8px;font:inherit;font-size:11px}.commentary-controls .primary{background:#e9a51b;color:#0b0b0a;border-color:#e9a51b;font-weight:900}.commentary-transcript-toggle{margin-top:13px;border:0;background:none;color:#e9a51b;padding:0;font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.commentary-transcript{display:none;margin-top:12px;padding-top:12px;border-top:1px solid #ffffff1f;color:#cbc7bf;font-size:13px;line-height:1.6}.commentary-transcript.open{display:block}@keyframes commentPulse{50%{box-shadow:0 0 0 12px #e9a51b18,0 12px 35px #0008}}@media(max-width:600px){.commentary-fab{right:14px;bottom:90px;width:52px;height:52px}.commentary-panel{right:16px;bottom:150px;max-height:48svh}.commentary-controls{grid-template-columns:1fr 1fr}.commentary-speed{grid-column:1/-1}}`;
const style=document.createElement('style');style.textContent=css;document.head.append(style);
let lesson;
try{lesson=await fetch('narration/dka.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()})}catch(e){console.error('Narration source unavailable',e);return}
const stages=lesson.stages||[];
const fab=document.createElement('button');fab.className='commentary-fab';fab.type='button';fab.setAttribute('aria-label','Open lecturer commentary');fab.innerHTML='🎧';
const panel=document.createElement('aside');panel.className='commentary-panel';panel.setAttribute('aria-label','Lecturer commentary');panel.innerHTML=`<div class="commentary-head"><div class="commentary-icon">◉</div><div class="commentary-title"><b>LECTURER COMMENTARY</b><small>Clinical reasoning alongside the lesson</small><div class="commentary-source">Gemini narration ready when recording is available</div></div></div><div class="commentary-controls"><button class="primary commentary-play">▶ Play</button><button class="commentary-restart">↺ Restart</button><button class="commentary-close">Close</button><select class="commentary-speed" aria-label="Playback speed"><option value="0.85">0.85×</option><option value="1" selected>1×</option><option value="1.15">1.15×</option><option value="1.3">1.3×</option></select></div><button class="commentary-transcript-toggle">Show transcript</button><div class="commentary-transcript"></div>`;
document.body.append(panel,fab);
const play=panel.querySelector('.commentary-play'),restart=panel.querySelector('.commentary-restart'),close=panel.querySelector('.commentary-close'),speed=panel.querySelector('.commentary-speed'),toggle=panel.querySelector('.commentary-transcript-toggle'),transcript=panel.querySelector('.commentary-transcript'),source=panel.querySelector('.commentary-source');
const backdrop=document.querySelector('.backdrop');
let lastStep=-1,audio=null,utter=null,paused=false,usingRecording=false,fallbackStarted=false;
function activeStep(){const els=[...document.querySelectorAll('.lesson-stage')];return Math.max(0,els.findIndex(s=>s.classList.contains('active')))}
function current(){return stages[activeStep()]||stages[0]}
function resetButton(){play.textContent='▶ Play';fab.classList.remove('playing');paused=false}
function stop(){if(audio){audio.pause();audio.currentTime=0;audio=null}if('speechSynthesis'in window)window.speechSynthesis.cancel();utter=null;usingRecording=false;fallbackStarted=false;resetButton()}
function setPlaying(){play.textContent='Ⅱ Pause';fab.classList.add('playing');paused=false}
function chooseVoice(){const vs=window.speechSynthesis?.getVoices?.()||[];return vs.find(v=>/en-GB/i.test(v.lang)&&/male|daniel|george|ryan|arthur|oliver/i.test(v.name))||vs.find(v=>/en-GB/i.test(v.lang))||vs.find(v=>/^en/i.test(v.lang))||vs[0]}
function fallbackSpeak(){if(fallbackStarted)return;fallbackStarted=true;usingRecording=false;source.textContent='Device voice fallback';if(!('speechSynthesis'in window)){transcript.classList.add('open');toggle.textContent='Hide transcript';resetButton();return}const s=current()?.script||'';window.speechSynthesis.cancel();utter=new SpeechSynthesisUtterance(s);utter.lang='en-GB';utter.rate=Number(speed.value);utter.pitch=.82;const v=chooseVoice();if(v)utter.voice=v;utter.onend=()=>{utter=null;fallbackStarted=false;resetButton()};utter.onerror=()=>{utter=null;fallbackStarted=false;resetButton()};window.speechSynthesis.speak(utter);setPlaying()}
function playCurrent(restartFromStart=false){const stage=current();if(!stage)return;fallbackStarted=false;if(paused&&!restartFromStart){if(usingRecording&&audio){audio.play();setPlaying();return}if(!usingRecording&&'speechSynthesis'in window){window.speechSynthesis.resume();setPlaying();return}}
stop();const path=`audio/dka/${stage.id}.mp3`;audio=new Audio(path);audio.preload='auto';audio.playbackRate=Number(speed.value);usingRecording=true;source.textContent='Gemini · high-quality recording';let failed=false;const fail=()=>{if(failed)return;failed=true;if(audio){audio.pause();audio=null}fallbackSpeak()};audio.onerror=fail;audio.onended=()=>{audio=null;usingRecording=false;resetButton()};const p=audio.play();if(p&&p.then)p.then(()=>setPlaying()).catch(fail);else setPlaying()}
function sync(){const i=activeStep();if(i!==lastStep){stop();lastStep=i;transcript.textContent=current()?.script||'';source.textContent='Gemini narration ready when recording is available'}}
function updateVisibility(){const open=!!backdrop?.classList.contains('open');fab.classList.toggle('visible',open);if(!open){stop();panel.classList.remove('open')}}
fab.onclick=()=>{sync();panel.classList.toggle('open');if(panel.classList.contains('open'))transcript.textContent=current()?.script||''};
close.onclick=()=>panel.classList.remove('open');
play.onclick=()=>{if(usingRecording&&audio&&!audio.paused){audio.pause();paused=true;play.textContent='▶ Resume';fab.classList.remove('playing');return}if(!usingRecording&&'speechSynthesis'in window&&speechSynthesis.speaking&&!speechSynthesis.paused){speechSynthesis.pause();paused=true;play.textContent='▶ Resume';fab.classList.remove('playing');return}playCurrent(false)};
restart.onclick=()=>playCurrent(true);
speed.onchange=()=>{if(usingRecording&&audio)audio.playbackRate=Number(speed.value);else if('speechSynthesis'in window&&speechSynthesis.speaking)fallbackSpeak()};
toggle.onclick=()=>{const open=transcript.classList.toggle('open');toggle.textContent=open?'Hide transcript':'Show transcript'};
const lessonScroll=document.querySelector('.lesson-scroll');if(lessonScroll)new MutationObserver(sync).observe(lessonScroll,{subtree:true,attributes:true,attributeFilter:['class']});if(backdrop)new MutationObserver(updateVisibility).observe(backdrop,{attributes:true,attributeFilter:['class']});
document.querySelector('.lesson-close')?.addEventListener('click',()=>{stop();panel.classList.remove('open');setTimeout(updateVisibility,0)});document.querySelector('.lesson-next')?.addEventListener('click',()=>setTimeout(sync,0));document.querySelector('.lesson-prev')?.addEventListener('click',()=>setTimeout(sync,0));
updateVisibility();sync();
})();
