(()=>{
const scripts=[
`So, here we have Maya, aged twelve, presenting with three weeks of increased thirst, passing a lot of urine and weight loss. Already, that should make you think about the differential diagnosis of polyuria and polydipsia. But today she also has abdominal pain, vomiting and unusually deep breathing. Let's look at the observations. Her heart rate is 128, so she's tachycardic. Her respiratory rate is 32 and the breaths are deep. Her temperature is 37.1, so there isn't an obvious fever here, and she is still alert, although clinically dry. Now put those findings together: polyuria, polydipsia, weight loss, vomiting, abdominal pain, tachycardia and deep rapid breathing. Don't jump straight to the diagnosis. Ask yourself: what single physiological disturbance could connect all of these findings?`,
`Before we go any further, commit to an answer. This is important. In real clinical reasoning you don't get to see the blood gas before you form an initial hypothesis. Gastroenteritis can explain vomiting and dehydration. Sepsis can explain tachycardia and acidosis. Appendicitis can explain abdominal pain and vomiting. But none of those comfortably explains three weeks of thirst, polyuria and weight loss together with deep breathing. Choose the diagnosis that explains both the preceding weeks and the acute deterioration.`,
`Now let's reconstruct the normal system before looking at what has failed. After a meal, glucose rises in the blood. Pancreatic beta cells sense that rise and release insulin. Insulin is not simply a glucose-lowering hormone. It is a whole-body signal that says fuel is available. In muscle and adipose tissue it promotes glucose uptake and storage. In the liver it suppresses further glucose production. In adipose tissue it switches off lipolysis. So insulin coordinates the fed state: use glucose, store energy and stop manufacturing emergency fuel. Keep that idea in mind, because DKA is what happens when that signal disappears.`,
`In type one diabetes, immune-mediated beta-cell destruction produces absolute insulin deficiency. Now notice the paradox: there is plenty of glucose in the bloodstream, but insulin-dependent tissues cannot use it normally, and the liver behaves as though the body is starving. Two pathways now run in parallel. First, glucose rises further because peripheral use falls and hepatic output continues. Once glucose spills into the urine it drags water and electrolytes with it. Second, the brake on lipolysis is removed. Free fatty acids reach the liver and are converted into ketone bodies. Those ketones are acids. So one missing hormone produces both severe dehydration and metabolic acidosis.`,
`Let's apply that mechanism to the symptoms. Why has Maya been passing so much urine? As the filtered glucose load rises, the kidney can no longer reabsorb all of it. Glucose remains in the renal tubule and holds water there osmotically. That produces a large urinary water loss: osmotic diuresis. The resulting dehydration raises plasma osmolality and stimulates thirst, so she drinks more. Her weight loss is also mechanistic: she is losing water and, because insulin is absent, breaking down fat and other energy stores despite having abundant glucose in the blood.`,
`Now look at the signs, especially the breathing. The lungs are not the primary problem. Ketone bodies generate a metabolic acidosis. The body cannot rapidly remove that acid through the kidneys, so it uses respiratory compensation. Chemoreceptors sense the fall in pH and ventilation increases. By breathing deeply and rapidly, Maya blows off carbon dioxide. That reduces the respiratory component of the acid load and partially compensates for the metabolic acidosis. This characteristic deep breathing is Kussmaul respiration. Her tachycardia, meanwhile, fits the intravascular volume depletion from osmotic diuresis.`,
`Now read the investigations as consequences rather than as a list of abnormal numbers. The glucose is high because insulin is absent and hepatic glucose output continues. The ketones are high because lipolysis and hepatic ketogenesis are unrestrained. The pH and bicarbonate are low because ketone acids consume bicarbonate buffering capacity. The potassium is the subtle result. A serum potassium of 4.7 may look reassuring, but total-body potassium is usually depleted because of urinary losses. Insulin deficiency and acidosis shift potassium out of cells, temporarily masking that depletion in the blood sample. Once insulin treatment starts, potassium moves back into cells and the serum level can fall quickly.`,
`Treatment becomes easier to remember if you connect each step to the mechanism. Fluids restore the circulating volume and improve renal perfusion. Insulin is essential because it switches off lipolysis and ketone production; the goal is not merely to lower the glucose. Potassium must be anticipated because total-body stores are depleted and insulin drives potassium back into cells. As glucose falls, dextrose may need to be added so insulin can continue long enough to clear the ketones and resolve the acidosis. In a child, use the current paediatric DKA guideline and local pathway rather than an adult protocol, with careful neurological monitoring throughout.`,
`Let's test whether you really own the mechanism rather than simply recognising Maya's numbers. This second child has known type one diabetes and a pump interruption. Her glucose is only 14.2, which is much less dramatic, but she has substantial ketonaemia and a venous pH of 7.19. The important lesson is that glucose alone does not define the metabolic emergency. Ask what the insulin deficiency is doing: is ketogenesis active, and has it produced metabolic acidosis? If the answer is yes, the same pathological process is operating even when the glucose is not extremely high.`,
`Finally, explain the entire case back to yourself as a causal chain. Beta-cell failure leads to absolute insulin deficiency. That causes hyperglycaemia through reduced glucose use and continued hepatic glucose production. Glycosuria produces osmotic diuresis, dehydration, thirst and tachycardia. Loss of insulin's brake on lipolysis causes ketone production and metabolic acidosis. The acidosis produces Kussmaul breathing as respiratory compensation. Treatment then reverses those mechanisms: fluid restores perfusion, insulin stops ketogenesis, and potassium is monitored and replaced because whole-body stores are depleted. If you can reconstruct that chain without memorising a symptom list, you understand DKA.`
];
const css=`.commentary-fab{position:fixed;z-index:145;right:24px;bottom:96px;width:58px;height:58px;border:1px solid #e9a51b;border-radius:50%;background:#e9a51b;color:#0b0b0a;display:none;place-items:center;font-size:24px;box-shadow:0 12px 35px #0008}.backdrop.open .commentary-fab{display:grid}.commentary-fab.playing{animation:commentPulse 1.7s ease-in-out infinite}.commentary-panel{position:fixed;z-index:144;right:24px;bottom:166px;width:min(390px,calc(100vw - 32px));max-height:min(540px,calc(100svh - 250px));overflow:auto;padding:20px;border:1px solid #ffffff26;background:#11110ff5;color:#f0eee8;box-shadow:0 20px 60px #000b;display:none}.commentary-panel.open{display:block}.commentary-head{display:flex;align-items:center;gap:12px}.commentary-icon{width:42px;height:42px;border-radius:50%;background:#e9a51b;color:#0b0b0a;display:grid;place-items:center;font-size:20px}.commentary-title{flex:1}.commentary-title b{display:block;font-size:13px;letter-spacing:.08em}.commentary-title small{color:#a7a49d}.commentary-controls{display:grid;grid-template-columns:1.5fr 1fr 1fr;gap:7px;margin-top:16px}.commentary-controls button,.commentary-speed{min-height:40px;border:1px solid #ffffff2b;background:#ffffff08;color:#f0eee8;padding:8px;font:inherit;font-size:11px}.commentary-controls .primary{background:#e9a51b;color:#0b0b0a;border-color:#e9a51b;font-weight:900}.commentary-transcript-toggle{margin-top:13px;border:0;background:none;color:#e9a51b;padding:0;font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.commentary-transcript{display:none;margin-top:12px;padding-top:12px;border-top:1px solid #ffffff1f;color:#cbc7bf;font-size:13px;line-height:1.6}.commentary-transcript.open{display:block}@keyframes commentPulse{50%{box-shadow:0 0 0 12px #e9a51b18,0 12px 35px #0008}}@media(max-width:600px){.commentary-fab{right:14px;bottom:84px;width:52px;height:52px}.commentary-panel{right:16px;bottom:146px;max-height:48svh}.commentary-controls{grid-template-columns:1fr 1fr}.commentary-speed{grid-column:1/-1}}`;
const style=document.createElement('style');style.textContent=css;document.head.append(style);
const fab=document.createElement('button');fab.className='commentary-fab';fab.type='button';fab.setAttribute('aria-label','Open lecturer commentary');fab.innerHTML='🎧';
const panel=document.createElement('aside');panel.className='commentary-panel';panel.setAttribute('aria-label','Lecturer commentary');panel.innerHTML=`<div class="commentary-head"><div class="commentary-icon">◉</div><div class="commentary-title"><b>LECTURER COMMENTARY</b><small>Clinical reasoning alongside the lesson</small></div></div><div class="commentary-controls"><button class="primary commentary-play">▶ Play</button><button class="commentary-restart">↺ Restart</button><button class="commentary-close">Close</button><select class="commentary-speed" aria-label="Playback speed"><option value="0.85">0.85×</option><option value="1" selected>1×</option><option value="1.15">1.15×</option><option value="1.3">1.3×</option></select></div><button class="commentary-transcript-toggle">Show transcript</button><div class="commentary-transcript"></div>`;
document.body.append(panel,fab);
const play=panel.querySelector('.commentary-play'),restart=panel.querySelector('.commentary-restart'),close=panel.querySelector('.commentary-close'),speed=panel.querySelector('.commentary-speed'),toggle=panel.querySelector('.commentary-transcript-toggle'),transcript=panel.querySelector('.commentary-transcript');let utter=null,paused=false,lastStep=-1;
function activeStep(){const stages=[...document.querySelectorAll('.lesson-stage')];return Math.max(0,stages.findIndex(s=>s.classList.contains('active')))}
function chooseVoice(){const vs=speechSynthesis.getVoices();return vs.find(v=>/en-GB/i.test(v.lang)&&/male|daniel|george|ryan|arthur|oliver/i.test(v.name))||vs.find(v=>/en-GB/i.test(v.lang))||vs.find(v=>/^en/i.test(v.lang))||vs[0]}
function stop(){speechSynthesis.cancel();utter=null;paused=false;play.textContent='▶ Play';fab.classList.remove('playing')}
function sync(){const i=activeStep();if(i!==lastStep){stop();lastStep=i;transcript.textContent=scripts[i]||''}}
function speak(fromStart=true){sync();if(!('speechSynthesis'in window))return;if(paused&&!fromStart){speechSynthesis.resume();paused=false;play.textContent='Ⅱ Pause';fab.classList.add('playing');return}speechSynthesis.cancel();utter=new SpeechSynthesisUtterance(scripts[lastStep]||'');utter.lang='en-GB';utter.rate=Number(speed.value);utter.pitch=.82;const v=chooseVoice();if(v)utter.voice=v;utter.onend=()=>{play.textContent='▶ Play';fab.classList.remove('playing');utter=null;paused=false};speechSynthesis.speak(utter);play.textContent='Ⅱ Pause';fab.classList.add('playing')}
fab.onclick=()=>{sync();panel.classList.toggle('open');if(panel.classList.contains('open'))transcript.textContent=scripts[activeStep()]||''};close.onclick=()=>panel.classList.remove('open');play.onclick=()=>{if(speechSynthesis.speaking&&!speechSynthesis.paused){speechSynthesis.pause();paused=true;play.textContent='▶ Resume';fab.classList.remove('playing')}else speak(!!utter===false)};restart.onclick=()=>speak(true);speed.onchange=()=>{if(speechSynthesis.speaking)speak(true)};toggle.onclick=()=>{const open=transcript.classList.toggle('open');toggle.textContent=open?'Hide transcript':'Show transcript'};
new MutationObserver(sync).observe(document.querySelector('.lesson-scroll'),{subtree:true,attributes:true,attributeFilter:['class']});
document.querySelector('.lesson-close')?.addEventListener('click',()=>{stop();panel.classList.remove('open')});document.querySelector('.lesson-next')?.addEventListener('click',()=>setTimeout(sync,0));document.querySelector('.lesson-prev')?.addEventListener('click',()=>setTimeout(sync,0));speechSynthesis.onvoiceschanged=()=>{};
})();