(()=>{
const DATA={
dka:{title:'DKA · Vomiting + deep breathing',sub:'Rebuild the case from insulin deficiency through hyperglycaemia, ketogenesis, dehydration, acidosis and clinical management.',back:'lesson.html?topic=dka',palette:['#ff9b82','#ffd2c5','#3a1c1a'],cards:[
{q:'What two linked problems follow from insulin deficiency?',a:'Hyperglycaemia with osmotic diuresis, and increased lipolysis with ketone production causing metabolic acidosis.',clue:'Think glucose handling and fat metabolism.',type:'Mechanism',icon:'↯'},
{q:'Why does polyuria occur in DKA?',a:'Glucose exceeds the renal threshold, causing glycosuria and osmotic diuresis.',clue:'Ask what glucose does once it spills into urine.',type:'Physiology',icon:'◌'},
{q:'Why is the breathing deep and rapid?',a:'Metabolic acidosis drives respiratory compensation, producing Kussmaul breathing.',clue:'The lungs are compensating for an acid-base problem.',type:'Clinical',icon:'≈'},
{q:'Which finding best explains a normal serum potassium despite total-body potassium depletion?',a:'Acidosis and insulin deficiency shift potassium out of cells while osmotic diuresis causes major total-body potassium loss.',clue:'Separate serum concentration from total body stores.',type:'Best finding',icon:'K⁺'},
{q:'Put the treatment logic in order: restore circulation, stop ketogenesis, reassess electrolytes.',a:'1. Restore circulation with fluids. 2. Give insulin to stop ketogenesis. 3. Monitor and replace potassium as treatment changes shifts.',clue:'Treat immediate physiology first, then the metabolic driver.',type:'Put in order',icon:'123'},
{q:'Why is insulin essential?',a:'Insulin suppresses lipolysis and ketogenesis and allows glucose uptake, addressing the initiating metabolic defect.',clue:'What process is actually driving ketone production?',type:'Mechanism',icon:'→'},
{q:'What is the key neurological concern during treatment?',a:'Cerebral injury; neurological state must be reassessed repeatedly during treatment.',clue:'Think about the brain during osmotic change.',type:'Clinical',icon:'◉'},
{q:'What is wrong with this pathway: insulin deficiency → less lipolysis → fewer ketones?',a:'Insulin deficiency increases lipolysis, so ketone production rises rather than falls.',clue:'Insulin normally restrains lipolysis.',type:'Spot the error',icon:'!'}],layers:[
['Normal fuel control','Insulin restrains hepatic glucose output and lipolysis while enabling cellular glucose use.',[['Insulin signal','Insulin keeps glucose and fat metabolism coordinated.'],['Liver','Insulin limits hepatic glucose production.'],['Adipose tissue','Insulin suppresses lipolysis and release of free fatty acids.']]],
['Insulin deficiency','Loss of insulin removes those restraints and creates two parallel metabolic problems.',[['Glucose rises','Hepatic glucose output increases while cellular uptake falls.'],['Fat breakdown rises','Lipolysis releases fatty acids for hepatic ketone production.'],['Counter-regulation','Stress hormones amplify hyperglycaemia and ketogenesis.']]],
['Metabolic consequences','Hyperglycaemia, glycosuria, ketone production and metabolic acidosis develop together.',[['Osmotic diuresis','Urinary glucose drags water and electrolytes with it.'],['Ketones','Acetoacetate and beta-hydroxybutyrate accumulate.'],['Potassium','Serum potassium can mislead because total body potassium is depleted.']]],
['Clinical picture','The metabolic disturbance becomes visible as dehydration, vomiting and compensatory breathing.',[['Dehydration','Polyuria and poor intake reduce circulating volume.'],['Kussmaul breathing','Respiratory compensation lowers carbon dioxide.'],['Neurology','Headache or altered consciousness can signal cerebral injury.']]],
['Management logic','Treatment reverses physiology in a deliberate sequence rather than simply lowering glucose.',[['Fluids','Restore circulation and renal perfusion.'],['Insulin','Stop ketogenesis and correct the core metabolic defect.'],['Monitoring','Track potassium, glucose, acid-base status and neurological state.']]]],summary:'DKA becomes easier to remember when every sign and treatment is linked back to the missing insulin signal.',resources:[['BSPED DKA guideline','UK paediatric DKA guideline and calculator.','https://www.bsped.org.uk/clinical-resources/bsped-dka-guidelines/'],['NICE NG18','Diabetes in children and young people.','https://www.nice.org.uk/guidance/ng18/chapter/recommendations'],['Cases','Return to the Cases library.','cases.html'],['Fundamentals','Continue with endocrine physiology.','fundamentals.html']]},
hyponatremia_case:{title:'Hyponatraemia case · Pneumonia → Na 122',sub:'Rebuild the child’s sodium fall from poor intake, IV fluids, non-osmotic ADH release and impaired free-water excretion.',back:'case-hyponatremia.html',palette:['#56bff2','#bdeaff','#102a3a'],cards:[
{q:'Why is sodium best thought of as a concentration?',a:'Because the measured value reflects sodium relative to water; adding water can lower sodium even without losing body sodium.',clue:'Think ratio, not just total amount.',type:'Mechanism',icon:'Na'},
{q:'Why does poor sodium intake alone rarely cause profound hyponatraemia?',a:'The kidney can markedly reduce urinary sodium loss through RAAS and aldosterone.',clue:'Ask what the kidney does when sodium delivery falls.',type:'Physiology',icon:'⌁'},
{q:'What does ADH do in the collecting duct?',a:'Via V2 receptors it promotes aquaporin-2 insertion, increasing water reabsorption.',clue:'Think water channels.',type:'Mechanism',icon:'H₂O'},
{q:'Which finding best explains pneumonia-associated hyponatraemia?',a:'Pulmonary disease, nausea, pain and stress can stimulate non-osmotic ADH release, reducing free-water excretion.',clue:'ADH can rise for reasons other than osmolality.',type:'Best finding',icon:'◍'},
{q:'Put the diagnostic logic in order: osmolality, urine concentration, clinical context.',a:'1. Confirm hypotonicity. 2. Ask whether ADH is active with urine osmolality. 3. Use urine sodium, volume state and context to identify why.',clue:'Start by proving the problem before naming the cause.',type:'Put in order',icon:'123'},
{q:'What is SIADH in practical terms?',a:'ADH remains active despite low plasma tonicity, so water is retained and sodium concentration falls.',clue:'The key problem is inappropriate water retention.',type:'Mechanism',icon:'↧'},
{q:'Why do neurological symptoms matter?',a:'Acute hypotonicity can cause cerebral oedema, making symptomatic hyponatraemia an emergency.',clue:'Where does water move when extracellular tonicity falls?',type:'Clinical',icon:'◉'},
{q:'What is wrong with this pathway: ADH rises → more dilute urine → sodium falls?',a:'ADH makes urine more concentrated, not more dilute, by increasing water reabsorption.',clue:'ADH conserves water.',type:'Spot the error',icon:'!'}],layers:[
['Starting child','Pneumonia, reduced intake and IV fluid exposure set the scene.',[['Illness','Pulmonary disease can drive non-osmotic ADH release.'],['Nausea and pain','Both are potent ADH stimuli.'],['IV fluid','Water administration becomes important when water excretion is impaired.']]],
['Hormonal response','ADH remains active even though falling tonicity should normally suppress it.',[['Hypothalamus','ADH-producing neurons integrate osmotic and non-osmotic signals.'],['Posterior pituitary','Stores and releases ADH into the circulation.'],['Non-osmotic drive','Illness and low effective volume can override osmotic suppression.']]],
['Kidney effect','ADH makes the collecting duct water-permeable and reduces free-water excretion.',[['V2 receptor','ADH binds V2 receptors on collecting-duct principal cells.'],['Aquaporin-2','Water channels are inserted into the apical membrane.'],['Urine','Urine stays inappropriately concentrated.']]],
['Serum sodium falls','Water gain relative to sodium lowers the measured sodium concentration.',[['Concentration','Serum sodium reflects sodium relative to body water.'],['Hypotonicity','True hypotonic hyponatraemia lowers extracellular osmolality.'],['Urine sodium','Helps interpret volume state and renal sodium handling.']]],
['Brain risk','Acute hypotonicity moves water into brain cells and can cause neurological symptoms.',[['Cerebral oedema','Water enters cells as extracellular tonicity falls.'],['Symptoms','Headache, nausea, drowsiness and seizures can occur.'],['Priority','Symptomatic acute hyponatraemia requires urgent treatment.']]]],summary:'The case makes sense when you see hyponatraemia as a water-balance problem rather than simply “not enough sodium”.',resources:[['NICE NG29','Paediatric IV fluid guidance.','https://www.nice.org.uk/guidance/ng29/chapter/recommendations'],['Clinical Concept','Go deeper into hyponatraemia.','concept-hyponatraemia.html'],['Cases','Return to the Cases library.','cases.html'],['Fundamentals','Review ADH and renal physiology.','fundamentals.html']]},
hyponatraemia:{title:'Hyponatraemia',sub:'Review sodium as a concentration problem: tonicity, ADH, urine osmolality, urine sodium, volume state and brain safety.',back:'concept-hyponatraemia.html',palette:['#4baee8','#a8ddf8','#11273a'],cards:[
{q:'What does serum sodium mainly tell you?',a:'It is primarily a marker of water balance relative to body sodium, not simply total body sodium.',clue:'Think concentration.',type:'Mechanism',icon:'Na'},
{q:'What is the first major diagnostic question?',a:'Is the hyponatraemia truly hypotonic? Check serum osmolality and clinical context.',clue:'Not every low sodium means low tonicity.',type:'Diagnostic',icon:'?'},
{q:'What does urine osmolality ≤100 mOsm/kg suggest?',a:'The kidney is maximally diluting urine and ADH is effectively suppressed.',clue:'Very dilute urine means water excretion is switched on.',type:'Best finding',icon:'100'},
{q:'What does urine osmolality >100 mOsm/kg suggest?',a:'ADH effect is present; the next question is why ADH is active.',clue:'Concentrated urine implies active water conservation.',type:'Mechanism',icon:'ADH'},
{q:'Put the framework in order: tonicity, ADH effect, cause, brain risk.',a:'1. Confirm hypotonicity. 2. Determine whether ADH is active. 3. Find why using urine sodium and volume/context. 4. Assess neurological risk.',clue:'Move from what the blood shows to what the kidney is doing.',type:'Put in order',icon:'123'},
{q:'Why can hypervolaemic patients still be hyponatraemic?',a:'Total body sodium may be increased, but total body water has increased even more.',clue:'Compare the relative rise in sodium and water.',type:'Mechanism',icon:'↥'},
{q:'Why does acute severe hyponatraemia cause neurological symptoms?',a:'Low extracellular tonicity drives water into brain cells, causing cerebral oedema.',clue:'Water follows osmotic gradients.',type:'Clinical',icon:'◉'},
{q:'What is wrong with this statement: chronic hyponatraemia should be corrected as fast as possible?',a:'Rapid correction can cause osmotic demyelination because the adapted brain is vulnerable to abrupt extracellular hypertonicity.',clue:'Chronic adaptation changes the brain’s osmolyte content.',type:'Spot the error',icon:'!'}],layers:[
['Confirm the problem','First establish that the low sodium represents true hypotonic hyponatraemia.',[['Serum osmolality','Confirms whether extracellular fluid is truly hypotonic.'],['Glucose','Hyperglycaemia can lower measured sodium while increasing tonicity.'],['Context','Lipids and proteins can occasionally affect measurement depending on method.']]],
['Is ADH active?','Urine osmolality tells you whether the kidney is appropriately excreting free water.',[['≤100 mOsm/kg','ADH is largely suppressed.'],['>100 mOsm/kg','ADH effect is present.'],['Interpretation','The key question becomes why ADH is on.']]],
['Why is ADH active?','Use volume state, urine sodium, drugs, renal and endocrine context.',[['Low effective volume','Baroreceptor signals can appropriately stimulate ADH.'],['SIADH pattern','ADH remains active despite hypotonicity.'],['Endocrine causes','Adrenal insufficiency and hypothyroidism can contribute.']]],
['Brain safety','The urgency depends heavily on symptoms and the rate of sodium fall.',[['Acute fall','Less time for brain adaptation means greater oedema risk.'],['Chronic fall','The brain sheds osmolytes to adapt.'],['Correction risk','Over-rapid correction can cause osmotic demyelination.']]],
['Management logic','Treat dangerous symptoms first, then correct carefully while addressing the cause.',[['Hypertonic saline','Used when severe neurological symptoms require urgent treatment.'],['Correction limits','Avoid excessive sodium rise.'],['Cause-specific care','Fluid strategy and treatment depend on the underlying mechanism.']]]],summary:'The recurring logic is: tonicity → ADH effect → why ADH is active → context → brain safety.',resources:[['NICE NG29','IV fluid therapy in children and young people.','https://www.nice.org.uk/guidance/ng29/chapter/recommendations'],['Related case','Open the paediatric hyponatraemia case.','case-hyponatremia.html'],['Fundamentals','Review water balance and ADH.','fundamentals.html'],['Clinical Concepts','Continue with fluid disorders.','clinical-concepts.html']]},
cortisol:{title:'Cortisol & the adrenal gland',sub:'Review the adrenal cortex, steroid synthesis, the HPA axis, cortisol physiology, adrenal insufficiency and congenital adrenal hyperplasia.',back:'fundamental-cortisol-guided.html',palette:['#e39b68','#ffd2a8','#3a2418'],cards:[
{q:'Which adrenal cortical zones make which hormones?',a:'Zona glomerulosa makes aldosterone, fasciculata makes cortisol, and reticularis makes adrenal androgens.',clue:'Remember G-F-R from outside to inside.',type:'Anatomy',icon:'◎'},
{q:'What is the common starting substrate for adrenal steroids?',a:'Cholesterol, transported into mitochondria by StAR and converted to pregnenolone by CYP11A1.',clue:'All adrenal steroids share the same starting molecule.',type:'Biochemistry',icon:'C'},
{q:'What is the HPA axis sequence?',a:'Hypothalamic CRH → pituitary ACTH → adrenal cortisol, with cortisol providing negative feedback.',clue:'Hypothalamus, pituitary, adrenal.',type:'Put in order',icon:'123'},
{q:'Why is cortisol important during physiological stress?',a:'It supports fuel availability, vascular responsiveness and restraint of excessive inflammatory signalling.',clue:'Think glucose, blood pressure and inflammation.',type:'Mechanism',icon:'↯'},
{q:'Which finding best fits primary rather than central adrenal insufficiency?',a:'Low cortisol with high ACTH and possible aldosterone deficiency points to primary adrenal failure.',clue:'Ask whether the adrenal gland itself has failed.',type:'Best finding',icon:'ACTH'},
{q:'Why can cortisol deficiency cause hypoglycaemia and hypotension?',a:'Glucose support and vascular responsiveness are impaired, especially during fasting or illness.',clue:'Cortisol helps maintain fuel and catecholamine responsiveness.',type:'Clinical',icon:'↓'},
{q:'What is the basic logic of congenital adrenal hyperplasia?',a:'Enzyme block → cortisol falls → ACTH rises → adrenal hyperplasia; precursors accumulate and are shunted into open pathways.',clue:'Think product down, precursor up, ACTH up.',type:'Mechanism',icon:'↺'},
{q:'What is wrong with this pathway: 21-hydroxylase deficiency → cortisol rises → ACTH falls?',a:'21-hydroxylase deficiency lowers cortisol, so negative feedback falls and ACTH rises.',clue:'An enzyme block reduces the product beyond the block.',type:'Spot the error',icon:'!'}],layers:[
['Adrenal anatomy','The cortex is organised into zones with distinct steroid outputs.',[['Glomerulosa','Produces aldosterone.'],['Fasciculata','Produces cortisol.'],['Reticularis','Produces adrenal androgens.']]],
['Steroid synthesis','All adrenal steroid pathways begin with cholesterol but diverge according to zone-specific enzymes.',[['StAR','Moves cholesterol into mitochondria.'],['CYP11A1','Converts cholesterol to pregnenolone.'],['Enzyme pattern','Different zones express different enzyme sets.']]],
['HPA control','Cortisol secretion is governed by CRH and ACTH with circadian and stress modulation.',[['CRH','Released from the hypothalamus.'],['ACTH','Stimulates the adrenal cortex.'],['Negative feedback','Cortisol suppresses CRH and ACTH.']]],
['Cortisol actions','Cortisol supports metabolism, circulation and controlled inflammatory responses.',[['Metabolism','Supports gluconeogenesis and fuel availability.'],['Circulation','Maintains vascular responsiveness to catecholamines.'],['Inflammation','Restrains excessive immune signalling.']]],
['When the system fails','Adrenal insufficiency and CAH can be understood by asking where the pathway is interrupted.',[['Primary failure','Low cortisol with high ACTH; aldosterone may also fall.'],['Central failure','Low cortisol with low or inappropriately normal ACTH.'],['CAH','Enzyme block lowers cortisol and redirects steroid precursors.']]]],summary:'The whole topic can be rebuilt from one map: adrenal zones + steroid synthesis + HPA control + cortisol actions + what happens when the pathway breaks.',resources:[['BSPED adrenal insufficiency','UK consensus guidance.','https://www.bsped.org.uk/adrenal-insufficiency'],['BSPED endocrine guidelines','Paediatric endocrine guideline repository.','https://www.bsped.org.uk/clinical-resources/guidelines/guidelines-repository/paediatric-endocrine-guidelines/'],['Clinical Concepts','Continue into adrenal crisis and endocrine disease.','clinical-concepts.html'],['Fundamentals','Return to Fundamentals.','fundamentals.html']]}}
;
const params=new URLSearchParams(location.search),key=params.get('lesson')||'dka',d=DATA[key]||DATA.dka,$=id=>document.getElementById(id);
$('lessonTitle').innerHTML=d.title.replace(' · ','<br><em>')+(d.title.includes(' · ')?'</em>':'');$('lessonSub').textContent=d.sub;$('backLink').href=d.back;
const perf=document.createElement('style');perf.textContent='@media(max-width:650px){.deck-card.active{will-change:transform;backface-visibility:hidden;-webkit-backface-visibility:hidden;transform:translate3d(0,0,0)}.deck-card.dragging{box-shadow:0 18px 45px #0009}.micro{animation:none}}';document.head.appendChild(perf);
let mode='smart',queue=[],results=[],history=[],current=null,startX=0,startY=0,lastX=0,lastY=0,dragging=false,axis=null,pointerId=null,raf=0;
function buildQueue(source=d.cards){queue=[...source];if(mode==='smart')queue.sort((a,b)=>(a.type==='Spot the error'?1:0)-(b.type==='Spot the error'?1:0));results=[];history=[];$('sessionEnd').classList.remove('show');$('deckStage').style.display='grid';renderDeck();updateProgress()}
function renderDeck(){const stage=$('deckStage');stage.innerHTML='';if(!queue.length){finishSession();return}const visible=queue.slice(0,3);visible.slice().reverse().forEach((card,rev)=>{const original=visible.length-1-rev;const el=document.createElement('article');el.className='deck-card '+(original===0?'active':original===1?'depth-1':'depth-2');const cardNumber=Math.max(1,d.cards.indexOf(card)+1);el.innerHTML=`<span class="swipe-cue left">Next</span><span class="swipe-cue right">Previous</span><div class="card-top"><span class="card-type">${card.type}</span><span class="card-count">${cardNumber} / ${d.cards.length}</span></div><div class="card-body"><div class="micro" aria-hidden="true">${card.icon}</div><div class="card-q">${card.q}</div><div class="card-clue">${card.clue}</div><div class="card-answer">${card.a}</div></div><div class="card-actions"><button type="button" class="clue">Clue</button><button type="button" class="reveal">Reveal answer</button></div><div class="confidence"><button type="button" data-score="again">Again</button><button type="button" data-score="unsure">Unsure</button><button type="button" data-score="got">Know it</button></div>`;stage.appendChild(el)});bindActive();updateNavigation()}
function reveal(c){const showing=c.classList.toggle('revealed');c.classList.toggle('gold',showing);const r=c.querySelector('.reveal');if(r)r.textContent=showing?'Show question':'Reveal answer';c.querySelector('.card-answer')?.setAttribute('aria-hidden',showing?'false':'true')}
function animateCard(direction,done){const c=document.querySelector('.deck-card.active');if(!c){done();return}c.classList.add(direction==='next'?'dismiss-left':'dismiss-right');setTimeout(done,220)}
function goNext(){if(queue.length<2)return;const first=queue.shift();history.push(first);queue.push(first);animateCard('next',()=>{renderDeck();updateProgress()})}
function goPrevious(){if(!history.length)return;const previous=history.pop();queue=queue.filter(card=>card!==previous);queue.unshift(previous);for(let i=results.length-1;i>=0;i--){if(results[i].card===previous){results.splice(i,1);break}}animateCard('previous',()=>{renderDeck();updateProgress()})}
function bindActive(){const c=document.querySelector('.deck-card.active');if(!c)return;current=queue[0];c.querySelector('.clue').addEventListener('click',e=>{e.stopPropagation();c.querySelector('.card-clue').classList.toggle('show')});c.querySelector('.reveal').addEventListener('click',e=>{e.stopPropagation();reveal(c)});c.querySelectorAll('[data-score]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();scoreCard(b.dataset.score,b)}));
const paint=()=>{raf=0;if(!dragging||axis!=='x')return;const dx=lastX-startX;c.style.transform=`translate3d(${dx}px,0,0) rotate(${dx*.018}deg)`;c.classList.toggle('drag-left',dx<-46);c.classList.toggle('drag-right',dx>46)};
const resetDrag=()=>{c.style.transform='';c.classList.remove('dragging','drag-left','drag-right')};
const endDrag=(cancel=false)=>{if(pointerId===null)return;if(raf){cancelAnimationFrame(raf);raf=0}const dx=lastX-startX,wasHorizontal=axis==='x';dragging=false;axis=null;try{c.releasePointerCapture?.(pointerId)}catch{}pointerId=null;if(cancel||!wasHorizontal||Math.abs(dx)<64){resetDrag();return}resetDrag();if(dx<0)goNext();else goPrevious()};
c.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;pointerId=e.pointerId;startX=lastX=e.clientX;startY=lastY=e.clientY;axis=null;dragging=false});
c.addEventListener('pointermove',e=>{if(e.pointerId!==pointerId)return;lastX=e.clientX;lastY=e.clientY;const dx=lastX-startX,dy=lastY-startY;if(!axis&&Math.hypot(dx,dy)>10){axis=Math.abs(dx)>Math.abs(dy)*1.15?'x':'y';if(axis==='x'){dragging=true;c.setPointerCapture?.(e.pointerId);c.classList.add('dragging')}}if(axis==='x'){e.preventDefault();if(!raf)raf=requestAnimationFrame(paint)}},{passive:false});
c.addEventListener('pointerup',e=>{lastX=e.clientX;lastY=e.clientY;endDrag(false)});c.addEventListener('pointercancel',()=>endDrag(true));c.addEventListener('lostpointercapture',()=>{if(pointerId!==null)endDrag(true)})}
function scoreCard(score,btn){const c=document.querySelector('.deck-card.active');if(!c)return;if(!c.classList.contains('revealed')){reveal(c);return}btn?.classList.add('selected');results.push({card:current,score});const first=queue.shift();history.push(first);if(score==='again'&&mode==='smart')queue.push(first);if(score==='unsure'&&mode==='smart'&&queue.length>1)queue.splice(Math.min(2,queue.length),0,first);c.classList.add(score==='got'?'dismiss-right':'dismiss-left');setTimeout(()=>{renderDeck();updateProgress()},220)}
function updateNavigation(){$('previousCard').disabled=!history.length;$('nextCard').disabled=queue.length<2}
$('previousCard').addEventListener('click',goPrevious);$('nextCard').addEventListener('click',goNext);
function updateProgress(){const answered=Math.min(d.cards.length,new Set(results.map(r=>r.card.q)).size),pct=Math.round(answered/d.cards.length*100);$('progressRing').style.setProperty('--p',pct+'%');$('progressNum').textContent=pct+'%';$('deckProgressLine').style.width=pct+'%';const weak=results.filter(r=>r.score!=='got').length;$('deckMini').innerHTML=`<b>${queue.length}</b> cards in the session<br><b>${weak}</b> marked for another look`;updateNavigation()}
function finishSession(){$('deckStage').style.display='none';$('sessionEnd').classList.add('show');const strong=results.filter(r=>r.score==='got'),weak=results.filter(r=>r.score!=='got');$('strongList').innerHTML=strong.length?strong.slice(-6).map(r=>`<div class="weak-item">${r.card.q}</div>`).join(''):'<div class="weak-item">No cards yet</div>';$('weakList').innerHTML=weak.length?weak.slice(-6).map(r=>`<div class="weak-item">${r.card.q}</div>`).join(''):'<div class="weak-item">Nothing to revisit</div>';$('reviewWeak').disabled=!weak.length;$('reviewWeak').onclick=()=>{queue=[...new Map(weak.map(r=>[r.card.q,r.card])).values()];results=[];$('sessionEnd').classList.remove('show');$('deckStage').style.display='grid';renderDeck();updateProgress()}}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;$('studyStatus').textContent=mode==='smart'?'Swipe to change cards · weak cards return automatically':'Swipe to change cards · one pass, no recycling';buildQueue()}));$('restartSession').addEventListener('click',()=>buildQueue());document.addEventListener('keydown',e=>{const c=document.querySelector('.deck-card.active');if(!c||document.activeElement?.matches('input,textarea'))return;if(e.key===' '){e.preventDefault();reveal(c)}if(e.key==='ArrowRight')goNext();if(e.key==='ArrowLeft')goPrevious()});buildQueue();
const shell=$('mapShell');shell.style.setProperty('--map-accent',d.palette[0]);shell.style.setProperty('--map-accent2',d.palette[1]);shell.style.setProperty('--map-wash',d.palette[2]);$('mapTitle').textContent='See the whole picture';$('mapIntro').textContent='One visual map of the whole lesson. Tap any node to zoom into that layer, then tap the key points for a concise explanation.';$('infoSummary').textContent=d.summary;
function renderOverview(){$('mapOverview').style.display='grid';$('mapDetail').classList.remove('show');$('mapBreadcrumb').innerHTML='<span>Overview</span>';$('mapOverview').innerHTML='<div class="map-path" aria-hidden="true"></div>';d.layers.forEach((layer,i)=>{const n=document.createElement('button');n.className='map-node';n.type='button';n.innerHTML=`<span class="map-orb">${String(i+1).padStart(2,'0')}</span><h3>${layer[0]}</h3><p>${layer[1]}</p><span class="zoom">Explore →</span>`;n.addEventListener('click',()=>openLayer(i));$('mapOverview').appendChild(n)})}
function openLayer(i){const layer=d.layers[i];$('mapOverview').style.display='none';$('mapDetail').classList.add('show');$('mapBreadcrumb').innerHTML='<button type="button" id="crumbOverview">Overview</button><span>›</span><span>'+layer[0]+'</span>';$('crumbOverview').addEventListener('click',renderOverview);$('detailKicker').textContent='Layer '+String(i+1).padStart(2,'0');$('detailTitle').textContent=layer[0];$('detailText').textContent=layer[1];$('detailLinks').innerHTML='';layer[2].forEach(([h,t])=>{const x=document.createElement('button');x.className='detail-hotspot';x.type='button';x.innerHTML=`<strong>${h}</strong><span class="prompt">Tap to explain</span><div class="extra">${t}</div>`;x.addEventListener('click',()=>x.classList.toggle('open'));$('detailLinks').appendChild(x)})}
renderOverview();
const rg=$('resourceGrid');d.resources.forEach(([h,t,u])=>{const x=document.createElement('article');x.className='resource';x.innerHTML=`<strong>${h}</strong><p>${t}</p><a href="${u}" ${/^https?:/.test(u)?'target="_blank" rel="noopener"':''}>Open resource →</a>`;rg.appendChild(x)});
function show(){const id=(location.hash||'#flashcards').slice(1);document.querySelectorAll('.tool-panel').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===id))}addEventListener('hashchange',show);show();
})();